### ISSUE TITLE
Update Wiki to Include Software Architecture

### ISSUE THREAD

**Issue by liborioc1** [liborioc1/Instagram_SOEN341#53]
Include a detailed diagram of the MVC architecture of our React Web App

**Comment by Salma-Elmahallawy** [comment]
![MCVDiagram](https://user-images.githubusercontent.com/50728005/110226972-73b59500-7ec1-11eb-96f9-dbc447e68ca7.png)
Is this diagram okay? Any modifications needed?

**Comment by liborioc1** [comment]
Looks great! When you move it over to the wiki add a small text description below it for context.

**Comment by Salma-Elmahallawy** [comment]
> Looks great! When you move it over to the wiki add a small text description below it for context.

Done! thank you :)
