### ISSUE TITLE
Update User Story Issues to Include Acceptance Tests

### ISSUE THREAD

**Issue by liborioc1** [liborioc1/Instagram_SOEN341#54]
The User Stories that were completed in Sprint 2 and that will be worked on in Sprint 3 should have acceptance tests in their comment section.

**Comment by Salma-Elmahallawy** [comment]
I have added the acceptance test to the new user story. @liborioc1 @NabilahRouf  please close when you are done.

**Comment by liborioc1** [comment]
> I have added the acceptance test to the new user story. @liborioc1 @NabilahRouf please close when you are done.

Nabilah and I have written them for the other user stories and reviewed yours. I will close now @Salma-Elmahallawy
